services: docker
language: python
python:
  - '3.6'

env:
  global:
    - VERSION=2.1.10
  matrix:
    - ARCH=i386
    - ARCH=amd64
    - ARCH=arm
    - ARCH=aarch64

install:
  - pip install pipenv
  - pipenv sync --dev

before_script:
  - ./build.sh $ARCH
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - pipenv check
  - pipenv run pytest -v
  - docker build -t tomsquest/docker-radicale:$ARCH -t tomsquest/docker-radicale:$ARCH.$VERSION --build-arg=VERSION=$VERSION --file Dockerfile.$ARCH .

deploy:
  provider: script
  script:
    echo "$DOCKER_PWD" | docker login -u "$DOCKER_USER" --password-stdin &&
    docker push tomsquest/docker-radicale:$ARCH &&
    docker push tomsquest/docker-radicale:$ARCH.$VERSION;
  on:
    branch: master
