services: docker
language: python
python:
  - '3.6'

env:
  matrix:
    - ARCH=i386
    - ARCH=amd64
    - ARCH=arm
    - ARCH=aarch64

install:
  - pip install pipenv
  - pipenv sync --dev

before_script:
  - ./build.sh $ARCH
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - pipenv check
  - pipenv run pytest -v

deploy:
  provider: script
  script:
    echo "$DOCKER_PWD" | docker login -u "$DOCKER_USER" --password-stdin &&
    docker build -t tomsquest/docker-radicale:$ARCH.$TRAVIS_TAG --file Dockerfile.$ARCH . &&
    docker push tomsquest/docker-radicale:$ARCH.$TRAVIS_TAG;
  skip_cleanup: true
  on:
    tags: true
